name = "chess-rs"
main = "build/worker/shim.mjs"
account_id = "fdbb5250325e731464a1827fff814852"
compatibility_date = "2023-03-22"
minify = true

[build]
command = "cargo install -q worker-build && pnpm tailwindcss -m -i assets/app.css -o static/app.css && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && pnpm tailwindcss -m -i assets/app.css -o static/app.css && worker-build --dev" }

[dev]
port = 8080
local_protocol = "http"